import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Pencil, PlusCircle, Shield, ShieldAlert, Trash2, Video, X } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { getAdminMediaSourceInput } from '../../services/firestore';
import { buildYouTubeEmbedUrl, isSafeHttpsUrl, parseYouTubeVideoId } from '../../services/videoSource';
import type { EnrollmentStatus, MediaStatus, MediaVisibility, UserRole, UserStatus, VideoLesson, VideoProvider } from '../../types/app';

const emptyForm = { title: '', description: '', thumbnailUrl: '', courseId: 'course-main', lessonId: '', provider: 'unset' as VideoProvider,
  youtubeInput: '', visibility: 'enrolled' as MediaVisibility, status: 'draft' as MediaStatus, durationSeconds: 0, order: 0, sourceConfirmed: false };

export const AdminDashboardModal: React.FC = () => {
  const { isAdminDashboardOpen, setIsAdminDashboardOpen, currentUser, users, loadUsers, setUserAccess, manageEnrollment, lessons, mediaLoading, mediaError, addLesson, editLesson, deleteLesson } = useApp();
  const [tab, setTab] = useState<'media' | 'users' | 'enrollments'>('media'); const [form, setForm] = useState(emptyForm);
  const [enrollmentForm, setEnrollmentForm] = useState({ uid: '', courseId: 'course-main', status: 'active' as EnrollmentStatus });
  const [editingId, setEditingId] = useState<string | null>(null); const [notice, setNotice] = useState<{ type: 'success' | 'error'; text: string } | null>(null); const [saving, setSaving] = useState(false);
  const youtubeId = useMemo(() => form.provider === 'youtube' ? parseYouTubeVideoId(form.youtubeInput) : null, [form.provider, form.youtubeInput]);
  const previewUrl = youtubeId ? buildYouTubeEmbedUrl(youtubeId) : null;

  useEffect(() => { if (isAdminDashboardOpen && currentUser?.role === 'admin') void loadUsers().catch(() => setNotice({ type: 'error', text: 'Không thể tải danh sách người dùng.' })); }, [isAdminDashboardOpen, currentUser?.role, loadUsers]);
  if (!isAdminDashboardOpen) return null;
  if (currentUser?.role !== 'admin') return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80"><div className="bg-[#001848] p-6 rounded-2xl text-center text-white"><ShieldAlert className="mx-auto text-red-500" /><p className="mt-3">Quyền truy cập bị từ chối.</p><button onClick={() => setIsAdminDashboardOpen(false)} className="mt-4">Đóng</button></div></div>;

  const edit = async (lesson: VideoLesson) => {
    setNotice(null); setSaving(true);
    try {
      const youtubeInput = lesson.provider === 'youtube' ? await getAdminMediaSourceInput(lesson.id) : '';
      setEditingId(lesson.id); setForm({ title: lesson.title, description: lesson.description, thumbnailUrl: lesson.thumbnailUrl, courseId: lesson.courseId,
        lessonId: lesson.lessonId, provider: lesson.provider, youtubeInput, visibility: lesson.visibility, status: lesson.status,
        durationSeconds: lesson.durationSeconds, order: lesson.order, sourceConfirmed: lesson.provider === 'youtube' });
    } catch { setNotice({ type: 'error', text: 'Không thể tải nguồn được bảo vệ để chỉnh sửa.' }); } finally { setSaving(false); }
  };

  const submitMedia = async (event: React.FormEvent) => {
    event.preventDefault(); setNotice(null);
    if (form.title.trim().length < 2 || form.title.trim().length > 150) return setNotice({ type: 'error', text: 'Tiêu đề phải có từ 2 đến 150 ký tự.' });
    if (!/^[A-Za-z0-9_-]{1,100}$/.test(form.courseId) || !/^[A-Za-z0-9_-]{1,100}$/.test(form.lessonId)) return setNotice({ type: 'error', text: 'Course ID và Lesson ID chỉ gồm chữ, số, gạch ngang hoặc gạch dưới.' });
    if (form.description.length > 2000 || (form.thumbnailUrl && !isSafeHttpsUrl(form.thumbnailUrl))) return setNotice({ type: 'error', text: 'Mô tả hoặc thumbnail không hợp lệ.' });
    if (form.provider === 'youtube' && (!youtubeId || !form.sourceConfirmed)) return setNotice({ type: 'error', text: youtubeId ? 'Hãy xác nhận cấu hình Unlisted và embedding.' : 'Link hoặc Video ID YouTube không hợp lệ.' });
    if (form.provider === 'cloudflare_stream' || form.provider === 'mux') return setNotice({ type: 'error', text: 'Provider signed playback chưa được kích hoạt.' });
    const input = { type: 'video' as const, title: form.title.trim(), description: form.description.trim(), thumbnailUrl: form.thumbnailUrl.trim(), courseId: form.courseId,
      lessonId: form.lessonId, provider: form.provider, visibility: form.visibility, status: form.status, durationSeconds: Number(form.durationSeconds), order: Number(form.order) };
    setSaving(true);
    try {
      const source = { provider: form.provider, youtubeInput: form.youtubeInput };
      if (editingId) await editLesson(editingId, input, source); else await addLesson(input, source);
      setNotice({ type: 'success', text: editingId ? 'Đã cập nhật video và nguồn được bảo vệ.' : 'Đã tạo video và nguồn được bảo vệ.' }); setForm(emptyForm); setEditingId(null);
    } catch (error) { setNotice({ type: 'error', text: error instanceof Error ? error.message : 'Không thể lưu video.' }); } finally { setSaving(false); }
  };
  const updateAccess = async (uid: string, role: UserRole, status: UserStatus) => { try { await setUserAccess(uid, role, status); setNotice({ type: 'success', text: 'Đã cập nhật quyền người dùng.' }); } catch { setNotice({ type: 'error', text: 'Không thể cập nhật quyền người dùng.' }); } };
  const submitEnrollment = async (event: React.FormEvent) => { event.preventDefault(); setNotice(null); if (!/^[A-Za-z0-9_-]{1,128}$/.test(enrollmentForm.uid) || !/^[A-Za-z0-9_-]{1,100}$/.test(enrollmentForm.courseId)) return setNotice({ type: 'error', text: 'UID hoặc Course ID không hợp lệ.' }); setSaving(true); try { await manageEnrollment(enrollmentForm.uid, enrollmentForm.courseId, enrollmentForm.status); setNotice({ type: 'success', text: 'Đã cập nhật quyền ghi danh.' }); } catch { setNotice({ type: 'error', text: 'Không thể cập nhật quyền ghi danh.' }); } finally { setSaving(false); } };
  const field = 'w-full px-3 py-2 bg-black/30 border border-white/15 rounded-xl text-white text-xs focus:outline-none focus:ring-2 focus:ring-amber-400';

  return <div className="fixed inset-0 z-50 flex items-center justify-center p-3 bg-black/85 text-white"><div className="w-full max-w-5xl bg-[#001848] rounded-2xl max-h-[92vh] overflow-y-auto border border-amber-500/30">
    <header className="sticky top-0 z-10 flex justify-between p-4 bg-[#00266b] border-b border-white/10"><h3 className="font-bold flex gap-2"><Shield className="text-[#fabb15]" />Quản trị YMM</h3><button aria-label="Đóng" onClick={() => setIsAdminDashboardOpen(false)}><X /></button></header>
    <nav className="flex flex-wrap gap-2 p-4 border-b border-white/10"><button onClick={() => setTab('media')} className={`px-4 py-2 rounded-xl ${tab === 'media' ? 'bg-[#fabb15] text-[#001848]' : 'bg-white/10'}`}><Video className="inline w-4 h-4 mr-2" />Media</button><button onClick={() => setTab('users')} className={`px-4 py-2 rounded-xl ${tab === 'users' ? 'bg-[#fabb15] text-[#001848]' : 'bg-white/10'}`}><Shield className="inline w-4 h-4 mr-2" />Người dùng</button><button onClick={() => setTab('enrollments')} className={`px-4 py-2 rounded-xl ${tab === 'enrollments' ? 'bg-[#fabb15] text-[#001848]' : 'bg-white/10'}`}>Ghi danh</button></nav>
    <main className="p-4 sm:p-6 space-y-4">{notice && <div className={`p-3 rounded-xl text-xs flex gap-2 ${notice.type === 'success' ? 'bg-emerald-500/20' : 'bg-red-500/20'}`}>{notice.type === 'success' ? <CheckCircle2 className="w-4 h-4" /> : <AlertCircle className="w-4 h-4" />}{notice.text}</div>}
      {tab === 'media' ? <div className="grid lg:grid-cols-2 gap-6"><form onSubmit={submitMedia} className="space-y-3 bg-white/5 p-4 rounded-2xl">
        <h4 className="font-bold text-[#fabb15] flex gap-2"><PlusCircle className="w-4 h-4" />{editingId ? 'Sửa video' : 'Thêm video'}</h4>
        <input className={field} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Tiêu đề" required /><textarea className={field} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Mô tả" />
        <div className="grid grid-cols-2 gap-2"><input className={field} value={form.courseId} onChange={(e) => setForm({ ...form, courseId: e.target.value })} placeholder="Course ID" required /><input className={field} value={form.lessonId} onChange={(e) => setForm({ ...form, lessonId: e.target.value })} placeholder="Lesson ID" required /></div>
        <input className={field} value={form.thumbnailUrl} onChange={(e) => setForm({ ...form, thumbnailUrl: e.target.value })} placeholder="Thumbnail HTTPS" />
        <div className="grid grid-cols-2 gap-2"><input className={field} type="number" min="0" value={form.durationSeconds} onChange={(e) => setForm({ ...form, durationSeconds: Number(e.target.value) })} aria-label="Thời lượng giây" /><input className={field} type="number" min="0" value={form.order} onChange={(e) => setForm({ ...form, order: Number(e.target.value) })} aria-label="Thứ tự" /></div>
        <select className={field} value={form.provider} onChange={(e) => setForm({ ...form, provider: e.target.value as VideoProvider, sourceConfirmed: false })}><option value="unset">Chưa cấu hình</option><option value="youtube">YouTube Unlisted</option><option value="cloudflare_stream" disabled>Cloudflare Stream (tương lai)</option><option value="mux" disabled>Mux (tương lai)</option></select>
        {form.provider === 'youtube' && <div className="space-y-2"><input className={field} value={form.youtubeInput} onChange={(e) => setForm({ ...form, youtubeInput: e.target.value, sourceConfirmed: false })} placeholder="URL YouTube hoặc Video ID" /><p className={`text-xs ${youtubeId ? 'text-emerald-300' : 'text-amber-300'}`}>{youtubeId ? 'Video ID hợp lệ. Source chỉ được lưu ở mediaSources.' : 'Chấp nhận watch, youtu.be, embed hoặc ID 11 ký tự.'}</p>{previewUrl && <div className="aspect-video"><iframe src={previewUrl} title="Xem trước video YouTube" className="w-full h-full" allow="encrypted-media; picture-in-picture" referrerPolicy="strict-origin-when-cross-origin" /></div>}<label className="flex gap-2 text-xs"><input type="checkbox" checked={form.sourceConfirmed} onChange={(e) => setForm({ ...form, sourceConfirmed: e.target.checked })} />Tôi xác nhận video là Unlisted, cho phép embedding và không bị giới hạn tuổi/bản quyền cản embed.</label></div>}
        <div className="grid grid-cols-2 gap-2"><select className={field} value={form.visibility} onChange={(e) => setForm({ ...form, visibility: e.target.value as MediaVisibility })}>{['enrolled','authenticated','public'].map((v) => <option key={v}>{v}</option>)}</select><select className={field} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as MediaStatus })}>{['draft','published','archived'].map((v) => <option key={v}>{v}</option>)}</select></div>
        <button disabled={saving} className="w-full py-2 bg-[#fabb15] text-[#001848] rounded-xl font-bold disabled:opacity-60">{saving ? 'Đang lưu…' : editingId ? 'Lưu thay đổi' : 'Tạo video'}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(emptyForm); }} className="w-full text-xs text-blue-200">Hủy chỉnh sửa</button>}
      </form><section className="space-y-3"><h4 className="font-bold">Media ({lessons.length})</h4>{mediaLoading ? <p>Đang tải…</p> : mediaError ? <p className="text-red-300">{mediaError}</p> : lessons.length === 0 ? <p className="text-blue-200">Chưa có media.</p> : lessons.map((lesson) => <article key={lesson.id} className="p-3 bg-white/5 rounded-xl flex justify-between gap-3"><div><p className="font-bold text-sm">{lesson.title}</p><p className="text-xs text-blue-200">{lesson.status} · {lesson.visibility} · {lesson.provider} · {lesson.sourceConfigured ? 'đã có nguồn' : 'chưa có nguồn'}</p></div><div className="flex gap-2"><button onClick={() => void edit(lesson)} aria-label="Sửa"><Pencil className="w-4 h-4" /></button><button onClick={() => void deleteLesson(lesson.id).catch(() => setNotice({ type: 'error', text: 'Không thể xóa media.' }))} aria-label="Xóa"><Trash2 className="w-4 h-4 text-red-400" /></button></div></article>)}</section></div>
      : tab === 'users' ? <section className="space-y-3">{users.length === 0 ? <p className="text-blue-200">Chưa có người dùng.</p> : users.map((user) => <article key={user.id} className="p-3 bg-white/5 rounded-xl flex flex-wrap justify-between gap-3"><div><p className="font-bold text-sm">{user.name}</p><p className="text-xs text-blue-200">{user.email}</p></div><div className="flex gap-2"><select className={field} value={user.role} disabled={user.id === currentUser.id} onChange={(e) => void updateAccess(user.id, e.target.value as UserRole, user.status)}><option value="user">user</option><option value="admin">admin</option></select><select className={field} value={user.status} disabled={user.id === currentUser.id} onChange={(e) => void updateAccess(user.id, user.role, e.target.value as UserStatus)}><option value="active">active</option><option value="disabled">disabled</option></select></div></article>)}</section>
      : <form onSubmit={submitEnrollment} className="max-w-xl space-y-3 bg-white/5 p-4 rounded-2xl"><h4 className="font-bold text-[#fabb15]">Cấp hoặc thu hồi quyền khóa học</h4><p className="text-xs text-blue-200">Dùng Firebase UID và Course ID. Client học viên không thể tự tạo hoặc sửa enrollment.</p><input className={field} value={enrollmentForm.uid} onChange={(e) => setEnrollmentForm({ ...enrollmentForm, uid: e.target.value })} placeholder="Firebase UID" required /><input className={field} value={enrollmentForm.courseId} onChange={(e) => setEnrollmentForm({ ...enrollmentForm, courseId: e.target.value })} placeholder="Course ID" required /><select className={field} value={enrollmentForm.status} onChange={(e) => setEnrollmentForm({ ...enrollmentForm, status: e.target.value as EnrollmentStatus })}><option value="active">active</option><option value="expired">expired</option><option value="revoked">revoked</option></select><button disabled={saving} className="w-full py-2 bg-[#fabb15] text-[#001848] rounded-xl font-bold">Cập nhật ghi danh</button></form>}
    </main></div></div>;
};
